export const formErrors = [
    {
      id: 0,
      name: "Empty form label",
      description: "Form label is empty",
      wcagLink: "",
      fix: "Add text to the empty form label",
    },
    {
      id: 1,
      name: "Form control missing label",
      description: "Form control doesn't have a label",
      wcagLink: "",
      fix: "Add a label for the form control",
    },
    {
      id: 2,
      name: "Form control multiple form labels",
      description: "Form control has more than 1 label",
      wcagLink: "",
      fix: "Leave only one label for the form control",
    },
    {
      id: 3,
      name: "Fieldset doesn't have legend",
      description: "Legend describes the elements contained by a fieldset",
      wcagLink: "",
      fix: "Add legend",
    },
    {
      id: 4,
      name: "Missing fieldset",
      description: "Two or more radio buttons or checkboxes with the same name are not contained by a fieldset",
      wcagLink: "",
      fix: "Add fieldset",
    },
    {
      id: 5,
      name: "Empty submit or button input value",
      description: "Submit or button input value is empty",
      wcagLink: "",
      fix: "Add text to value",
    },
    {
      id: 6,
      name: "Image input must have alt text",
      description: "Image input must have alt text",
      wcagLink: "",
      fix: "Add alt text to image inputs",
    },
    {
      id: 7,
      name: "Form elements should have a visible label",
      description: "Form elements should have a visible label",
      wcagLink: "",
      fix: "Ensures that every input that requires a label is has a label other than the title or aria-describedby attributes",
    },
    {
      id: 8,
      name: "autocomplete attribute must be used correctly",
      description: "autocomplete attribute must be used correctly",
      wcagLink: "",
      fix: "Confirm that the autocomplete attribute is set with the appropriate value",
    },
]