export const semanticErrors = [
    {
      id: 0,
      name: "No first level heading",
      description: "No first level heading on the page",
      wcagLink: "",
      fix: "Add h1 tag",
    },
    {
      id: 1,
      name: "Skipped heading level",
      description: "Heading level skipped",
      wcagLink: "",
      fix: "Reorder headings and make sure levels are in order",
    },
    {
      id: 2,
      name: "Possible heading",
      description: "A <p> tag looks like a heading",
      wcagLink: "",
      fix: "Use a heading element",
    },
    {
      id: 3,
      name: "No headings",
      description: "No headings on the page",
      wcagLink: "",
      fix: "Add headings",
    },
    {
      id: 4,
      name: "No page regions",
      description: "No page regions or aria landmarks on the page",
      wcagLink: "",
      fix: "Use semantic tags to define regions",
    },
    {
      id: 5,
      name: "Page must have one <main> tag",
      description: "Page must have a main tag",
      wcagLink: "",
      fix: "Add main tag",
    },
    {
      id: 6,
      name: "Page should not have more than one main tag",
      description: "Page must have only one main tag",
      wcagLink: "",
      fix: "Leave only one main tag",
    },
    {
      id: 7,
      name: "Page should not have more than one banner landmark",
      description: "Page must have only one banner landmark",
      wcagLink: "",
      fix: "Leave only one banner landmark",
    },
    {
      id: 8,
      name: "Page should not have more than one contentinfo landmark",
      description: "Page must have only one contentinfo landmark",
      wcagLink: "",
      fix: "Leave only one contentinfo landmark",
    },
    {
      id: 9,
      name: "Header or role=\"banner\" landmark should not be contained in another landmark",
      description: "Header or role=\"banner\" landmark should not be contained in another landmark",
      wcagLink: "",
      fix: "Header or role=\"banner\" landmark should be at top level",
    },
    {
      id: 10,
      name: "Aside or role=\"complementary\" should not be contained in another landmark",
      description: "Aside or role=\"complementary\" should not be contained in another landmark",
      wcagLink: "",
      fix: "Aside or role=\"complementary\" should be top level",
    },
    {
      id: 11,
      name: "Footer or role=\"contentinfo\" landmark should not be contained in another landmark",
      description: "Footer or role=\"contentinfo\" landmark should not be contained in another landmark",
      wcagLink: "",
      fix: "Footer or role=\"contentinfo\" landmark should be top level",
    },
    {
      id: 12,
      name: "Main or role=\"main\" landmark should not be contained in another landmark",
      description: "Main or role=\"main\" landmark should not be contained in another landmark",
      wcagLink: "",
      fix: "Main or role=\"main\" landmark should be top level",
    },
    {
      id: 13,
      name: "Page content should be contained by landmarks",
      description: "Page content should be contained by landmarks",
      wcagLink: "",
      fix: "Ensure all page content is contained by landmarks",
    },
    {
      id: 14,
      name: "ul and ol must only directly contain li, script or template elements",
      description: "ul and ol must only directly contain li, script or template elements",
      wcagLink: "",
      fix: "Ensure that lists are structured properly",
    },
    {
      id: 15,
      name: "li elements must be contained in an ul or ol",
      description: "li elements must be contained in an ul or ol",
      wcagLink: "",
      fix: "Ensures li elements are used semantically",
    },
    {
      id: 16,
      name: "dl elements must only directly contain properly-ordered dt and dd groups, script, template or div elements",
      description: "dl elements must only directly contain properly-ordered dt and dd groups, script, template or div elements",
      wcagLink: "",
      fix: "Ensure that all dl elements are structured correctly.",
    },
    {
      id: 17,
      name: "dt and dd elements must be contained by a dl element",
      description: "dt and dd elements must be contained by a dl element",
      wcagLink: "",
      fix: "Ensure that all dt and dd elements are contained dl.",
    },
    {
      id: 18,
      name: "page must have means to bypass repeated blocks",
      description: "page must have means to bypass repeated blocks",
      wcagLink: "",
      fix: "each page must have a main landmark to provide a mechanism to bypass repeated blocks of content or interface elements",
    },
]