import { ariaAllowedRole } from "./aria-allowed-role/aria-allowed-role.js";
import { ariaValidAttributeValues } from "./aria-valid-attribute-values/aria-valid-attribute-values.js";
import { ariaCommandsNames } from "./aria-command-names/aria-command-names.js";
import { ariaConditionalAttributes } from "./aria-conditional-attributes/aria-conditional-attributes.js";
import { ariaDialogAndAlertDialogNames } from "./aria-dialog-and-alertdialog-names/aria-dialog-and-alertdialog-names.js";
import { ariaHiddenFocusableOrWithFocusableChildren } from "./aria-hidden-focusable-or-with-focusable-children/aria-hidden-focusable-or-with-focusable-children.js";
import { ariaInputFieldNames } from "./aria-input-field-names/aria-input-field-names.js";
import { ariaMeterNames } from "./aria-meter-names/aria-meter-names.js";
import { ariaProgressbarNames } from "./aria-progressbar-names/aria-progressbar-names.js";
import { ariaRoleProhibitedAttributes } from "./aria-role-prohibited-attributes/aria-role-prohibited-attributes.js";
import { ariaRoleRequiredAriaAttributes } from "./aria-role-required-aria-attributes/aria-role-required-aria-attributes.js";
import { ariaRoleRequiredChildren } from "./aria-role-required-children/aria-role-required-children.js";
import { ariaRoleRequiredParent } from "./aria-role-required-parent/aria-role-required-parent.js";
import { ariaRoleAllowedAriaAttributes } from "./aria-role-allowed-aria-attributes/aria-role-allowed-aria-attributes.js";
import { ariaRoleValidValues } from "./aria-roles-valid-values/aria-roles-valid-values.js";
import { ariaTextNoFocusableChildren } from "./aria-text-no-focusable-children/aria-text-no-focusable-children.js";
import { ariaToggleFieldNames } from "./aria-toggle-field-names/aria-toggle-field-names.js";
import { ariaTooltipNames } from "./aria-tooltip-names/aria-tooltip-names.js";
import { ariaTreeitemNames } from "./aria-treeitem-names/aria-treeitem-names.js";
import { ariaValidAttributes } from "./aria-valid-attributes/aria-valid-attributes.js";
import { hasAriaDeprecatedRoles } from "./has-aria-deprecated-roles/has-aria-deprecated-roles.js";
import { hasAriaHiddenBody } from "./has-aria-hidden-body/has-aria-hidden-body.js";
import { hasRolePresentationOrNoneConflict } from "./has-role-presentation-or-none-conflict/has-role-presentation-or-none-conflict.js";

export async function ariaAudit(auditResults) {
    await hasAriaHiddenBody(auditResults);
    await ariaCommandsNames(auditResults);
    await ariaMeterNames(auditResults);
    await ariaProgressbarNames(auditResults);
    await ariaTooltipNames(auditResults);
    await hasAriaDeprecatedRoles(auditResults);
    await ariaInputFieldNames(auditResults);
    await ariaToggleFieldNames(auditResults);
    await ariaHiddenFocusableOrWithFocusableChildren(auditResults);
    await ariaRoleValidValues(auditResults);
    await ariaDialogAndAlertDialogNames(auditResults);
    await ariaTextNoFocusableChildren(auditResults);
    await ariaAllowedRole(auditResults);
    await ariaTreeitemNames(auditResults);
    await ariaValidAttributeValues(auditResults);
    await ariaValidAttributes(auditResults);
    await ariaRoleAllowedAriaAttributes(auditResults);
    await ariaRoleRequiredAriaAttributes(auditResults);
    await ariaRoleRequiredChildren(auditResults);
    await ariaRoleRequiredParent(auditResults);
    await ariaRoleProhibitedAttributes(auditResults);
    await ariaConditionalAttributes(auditResults);
    await hasRolePresentationOrNoneConflict(auditResults);
}